3727/fix500 invalid GitHub auth
dockstore/dockstore pull request #3813
Opened 2020-09-15 20:05 UTC by nrzhao4

- accessToken gets set to null and doesn't throw the exception
- now checks if accessToken is null, returns 400 if it is null

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`

2020-09-16 18:11 UTC, garyluu commented on dockstore-webservice/src/test/java/io/dockstore/webservice/helpers/GitHubHelperTest.java
> +    public void testGetGitHubAccessToken() {
Add description for test

2020-09-16 18:19 UTC, coverbeck requested changes

2020-09-16 18:19 UTC, coverbeck commented on dockstore-webservice/src/test/java/io/dockstore/webservice/helpers/GitHubHelperTest.java
> +            GitHubHelper.getGitHubAccessToken(CODE, GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET);
You should add a `fail()` after this line; if the function didn't throw an exception, your test will pass, which isn't what you want.

2020-09-18 20:09 UTC, denis-yuen approved these changes

2020-09-18 22:00 UTC, coverbeck approved these changes

2020-09-18 22:53 UTC, garyluu approved these changes

2020-09-21 13:47 UTC, merged