new endpoint to unban a user
dockstore/dockstore pull request #4455
Opened 2021-09-08 18:32 UTC by NatalieEO

https://ucsc-cgl.atlassian.net/browse/SEAB-3170
I wasn't sure how to write a test for getting a new Dockstore token. But when a user logs in, a new token is created if we don't find one in the db.

2021-09-08 19:37 UTC, garyluu commented on dockstore-webservice/src/main/resources/openapi3/openapi.yaml
> +      description: Reactive a user that has been terminated
reactivate

2021-09-08 19:37 UTC, garyluu commented on dockstore-webservice/src/main/resources/openapi3/openapi.yaml
> +    get:
probably should not be GET

2021-09-08 19:37 UTC, garyluu commented on dockstore-webservice/src/main/resources/swagger.yaml
> +    get:
don't need swagger for new endpoints

2021-09-08 22:01 UTC, denis-yuen approved these changes

2021-09-08 23:43 UTC, coverbeck approved these changes
>  wasn't sure how to write a test for getting a new Dockstore token. 

It seems like your tests work, I'm not sure I follow. But you can always insert a new token directly into the DB if that's what you mean.

Left a comment which I have mixed feelings about. Will defer on that one.

2021-09-08 23:43 UTC, coverbeck commented on dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java
> +    @Operation(operationId = "reactivateUser", description = "Reactivate a user that has been terminated", security = @SecurityRequirement(name = OPENAPI_JWT_SECURITY_DEFINITION_NAME))
"...has been terminated" -> "...has been banned"? Not sure of our exact terminology.

2021-09-08 23:43 UTC, coverbeck commented on dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java
> +    public boolean reactivateUser(@ApiParam(hidden = true) @Parameter(hidden = true, name = "user") @Auth User authUser,
From a RESTful purist-ish perspective:

1. You should return the user, not a boolean. The HTTP status code will indicate success or failure.
2. I don't think you should take up `/user/{userId}` for this feature alone

You could instead create a `UserLite` (I wouldn't use that name) class that so far only has one optional property, `banned`. Then if we choose to allow additional editable things, we just add to that class.

On the other hand, this is an endpoint that we'll hopefully never have to invoke, at least in its current incarnation, so, worth the effort? I don't know.

2021-09-09 14:07 UTC, garyluu requested changes
No patch/put without body. Swagger complains about it and so will I.

2021-09-09 19:58 UTC, david4096 commented
It might be good to clarify the language used around this feature throughout the code base. Since we use "ban" in the code that seems like a better term than terminate.

2021-09-09 19:58 UTC, david4096 approved these changes

2021-09-10 23:36 UTC, coverbeck reviewed
I think there are 2 ways to deal with this:

1. Continue with this approach and model more like we do limits, returning/requiring a Ban object. Although I'm having hard time finding justification/precendent for that pattern (that I did). :(
2. Go back to the way you had it before, with separate methods for ban/unban. But make the ban on `/user/<userid>` instead of `/user/<userId>/banStatus`, use PATCH, and require an object to modify the user.

This may all seem esoteric and not matter that much since from our perspective we end up using client libraries any ways, and to a degree that's true, but it's generally good to follow best RESTful practices.

Curious what others think.

2021-09-10 23:36 UTC, coverbeck commented on dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java
> +        if (isBanned == targetUser.isBanned()) {
I lean towards not throwing an error for this. Make it idempotent, and if it's the same as before, just proceed.

2021-09-10 23:36 UTC, coverbeck commented on dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java
> +    @Operation(operationId = "banUser", description = "Update banned status of user if possible. Removes all tokens for banned users.", security = @SecurityRequirement(name = OPENAPI_JWT_SECURITY_DEF
I would get rid of "if possible". It's true, but it's also true for all of our operations.

2021-09-10 23:36 UTC, coverbeck commented on dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java
> +    public User banUser(
This should return the resource you are modifying. `banned` is not part of `User`, so I would return a `Banned` object (and expect one for the input). Like we do for [limits](https://github.com/dockstore/dockstore/blob/07a2b884b440bf480ad67297dccad0e718792b0c/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java#L877).

2021-09-10 23:36 UTC, coverbeck commented on dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java
> +    @PATCH
I would make this a PUT if you follow my other comment to return a Banned object instead of a User object

2021-09-13 13:58 UTC, denis-yuen commented
>     1. Continue with this approach and model more like we do limits, returning/requiring a Ban object. Although I'm having hard time finding justification/precendent for that pattern (that I did). :(

Maybe https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/api/PublishRequest.java and associated endpoint

2021-09-13 18:25 UTC, garyluu approved these changes
Assuming the endpoint returns 204 and not 200

2021-09-13 18:25 UTC, garyluu commented on dockstore-webservice/src/main/resources/openapi3/openapi.yaml
> +          '*/*':
missing something

2021-09-14 16:06 UTC, coverbeck approved these changes
Second Gary's comment that this should return 204. Maybe it does already, please verify.

2021-09-17 19:56 UTC, Richard-Hansen approved these changes

2021-09-23 17:33 UTC, merged